name: CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with default repo setup
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install npm packages
      - run: npm ci

      - name: Check types by running TypeScript complier
      - run: npm run check-types

      - name: Check code format by running Prettier
      - run: npm run check-format

      - name: Catch logical mistakes by running ESLint
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with default repo setup
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install npm packages
      - run: npm ci

      - name: Run tests using jest-junit reporter
      - run: npm run test-report

      - name: Publish test report
      - uses: dorny/test-reporter@v1
      if: success() || failure() 
      with:
        name: Test Report
        path: reports/*.xml
        reporter: jest-junit

  build and deploy:
    runs-on: ubuntu-latest
    needs: [validate, test]
    steps:
      - name: Checkout repo with default repo setup
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install npm packages
      - run: npm ci

      - name: Create a production build directory
      - run: npm run build

      - name: Deploy to GitHub
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'henghaopu'
          user_email: 'henghaopu@gmail.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }} 
